apiVersion: v1
entries:
  rackspacespot:
  - annotations:
      catalog.cattle.io/display-name: Rackspace Spot
      catalog.cattle.io/kube-version: '>= 1.16.0-0'
      catalog.cattle.io/namespace: cattle-ui-plugin-system
      catalog.cattle.io/os: linux
      catalog.cattle.io/permits-os: linux, windows
      catalog.cattle.io/rancher-version: '>= 2.10.0-0'
      catalog.cattle.io/release-name: rackspacespot
      catalog.cattle.io/scope: management
      catalog.cattle.io/ui-component: plugins
      catalog.cattle.io/ui-extensions-version: '>= 3.0.0 < 4.0.0'
    apiVersion: v2
    appVersion: v0.0.1
    created: "2026-05-11T13:10:15.876807676Z"
    description: Rancher cluster driver and UI extension for Rackspace Spot.
    digest: 72789c678d29a6e0f5efd0b9eadbbc630c2155b37f958abee5c1cccfd720d6a7
    home: https://github.com/teamzuzu/rancher-rackspace-spot-driver
    name: rackspacespot
    sources:
    - https://github.com/teamzuzu/rancher-rackspace-spot-driver
    type: application
    urls:
    - https://teamzuzu.github.io/rancher-rackspace-spot-driver/charts/rackspacespot-0.0.1.tgz
    version: 0.0.1
generated: "2026-05-11T13:10:15.876260334Z"
