kontainerDriver:
  url: "https://github.com/teamzuzu/rancher-rackspace-spot-driver/releases/download/v0.1.9/rancher-rackspace-spot-driver_linux_amd64.tar.gz"
  checksum: "eb49c98bbf26c2f8fabee906451522d7bee0598e1386e5b7110400c0292f45c1"
uiPlugin:
  endpoint: "https://teamzuzu.github.io/rancher-rackspace-spot-driver/extensions/rackspacespot/0.1.9"
