{{- if .Values.credentials.secretName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rackspacespot-credential-reader
  namespace: cattle-system
  labels:
    app.kubernetes.io/name: rackspacespot
    app.kubernetes.io/version: {{ trimPrefix "v" .Chart.AppVersion | quote }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: [{{ .Values.credentials.secretName | quote }}]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rackspacespot-credential-reader
  namespace: cattle-system
  labels:
    app.kubernetes.io/name: rackspacespot
    app.kubernetes.io/version: {{ trimPrefix "v" .Chart.AppVersion | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rackspacespot-credential-reader
subjects:
  - kind: ServiceAccount
    name: rancher
    namespace: cattle-system
{{- end }}
